version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
  jobs:
    pre_build:
      - python docs/pre_build_markdown.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

formats:
  - pdf

sphinx:
  configuration: docs/conf.py
