name: tests-environment
channels:
  - defaults
  - conda-forge
dependencies:
  - scipy
  - matplotlib
  - cython
  - pyyaml
  - dill
  - coverage
  - pytest
  - pandas
  - iminuit
  - mpi4py
  - openmpi
  - pip
  - setuptools>=77
  - pip:
    - ruff
    - flaky
    - pytest-xdist
    - pytest-cov
    - camb
    - -r requirements.txt
