#!/bin/bash

# Sample job template for Univa Grid Engine cluster (e.g. Apollo in Sussex)
# Python script replaces placeholders inside CURLY BRACKETS with values given
# in the python script

# --- Job and queue info -------------------------------------------------------
#$ -N {JOBNAME}
#$ -q {QUEUE}
#$ -jc {JOBCLASS}
#$ -cwd
#$ -V
# --- Resource allocation with optimal MPI+OpenMP interaction ------------------
#$ -pe openmpi_mixed_{CHAINSPERNODE} {NUMMPI}
#$ -binding pe striding:{CHAINSPERNODE}:{OMP}
#$ -R y
#$ -l exclusive=True
export OMP_NUM_THREADS={OMP}
#$ -l h_rt={WALLTIME}
# --- Logging ------------------------------------------------------------------
#$ -j y
#$ -o {LOGDIR}
# --- E-mail notifications (optional) ------------------------------------------
#     (add your e-mail and remove one #+space from the following 2 lines)
# #$ -m bea
# #$ -M your_email@here.com

# Your C/Fortran compiler + MPI + Python here
module load python/2.7.12
module load gcc/5.4.0
module load openmpi/2.0.1/gcc/5.4.0

cd {ROOTDIR}

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Job ID is $JOB_ID
echo Hostfile `cat $PE_HOSTFILE`

# Run command

{COMMAND}


## Set things to be used by the python script,
## which extracts text from here with ##XX: ...##

## Command to use for each run in the batch
##RUN: mpirun -n $NSLOTS {PROGRAM} {INI}##

## Commands to submit and delete
##DEFAULT_qsub: qsub##
##DEFAULT_qdel: qdel##

## These defaults specific to Sussex apollo
##DEFAULT_QUEUE: mps.q##
##DEFAULT_JOBCLASS: mps.long##
