name: Build Documentation as Markdown

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
      - 'cobaya/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[docs]
        pip install sphinx-markdown-builder

    - name: Build documentation as Markdown
      run: |
        mkdir -p docs/_build
        python docs/build_docs_to_markdown.py --exclude "cluster_amazon,devel" --output docs/_build/cobaya_docs_combined.md

    - name: Upload documentation as artifact
      uses: actions/upload-artifact@v4
      with:
        name: cobaya-docs-markdown
        path: docs/_build/cobaya_docs_combined.md
